name       : xboard
version    : 4.9.1
release    : 8
source     :
    - http://ftp.gnu.org/gnu/xboard/xboard-4.9.1.tar.gz : 2b2e53e8428ad9b6e8dc8a55b3a5183381911a4dae2c0072fa96296bbb1970d6
homepage   : http://www.gnu.org/software/xboard/
license    : GPL-3.0
component  : games.strategy
summary    : xboard (GUI for chess games)
description: |
    xboard is a GUI for chess in all its major forms.
builddeps  :
    - pkgconfig(cairo-svg)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(librsvg-2.0)
setup      : |
    %configure --with-gamedatadir=/usr/share/xboard --with-gtk
build      : |
    %make
install    : |
    %make_install
    sed -i "s:Exec=xboard:Exec=xboard -ncp:g" $installdir/usr/share/applications/xboard.desktop
